spring.application.name=medimindbackend
spring.data.mongodb.uri=mongodb+srv://admin:admin@cluster0.uabq7bv.mongodb.net/medimind?retryWrites=true&w=majority

jwt.secret=medimindsecretkeymedimindsecretkey

groq.api.key=${GROQ_API_KEY}
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=abhishekjaiswal6802@gmail.com
spring.mail.password=tvgu dbax oqsk eehu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=8080